apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-cache
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.31
    path: /srv/nfs/ntfy
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
