apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - helmrelease.yaml
patches:
  - path: runtime-config-patch.yaml
configMapGenerator:
  - name: gtnh-runtime-config
    files:
      - jvm.options
      - merge-forge-cfg.sh
      - serverutilities.patch.cfg
configurations:
  - kustomizeconfig.yaml
