apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - serviceaccount.yaml
  - gtnh
  - stone-block-4
configMapGenerator:
  - name: app-backup-config
    files:
      - credential-configuration.json
      - upload.sh
