apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-nfs
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: nfs
      parameters:
        server: 192.168.2.31
        share: /srv/nfs
        subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
        onDelete: retain
        mountPermissions: "0777"
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.1
