apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
