[Interface]
PrivateKey = @PRIVATE_KEY@
Address = 10.90.0.2/24

[Peer]
PublicKey = DhehYIKeCAt+u1XYU647ZJf/z1frLKLJEoLkFfesMEo=
AllowedIPs = 10.90.0.1/32
Endpoint = 172.235.215.105:51820
PersistentKeepalive = 25
