apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:QKdyys3iCLz14c+EWOvRAz4=,iv:Tue8z1pZeH9QEfky2e+OaIKXVVCxOQbjjsunVZprFWE=,tag:Cu+hIoolddxpviBoOvx5YA==,type:str]
    clientSecret: ENC[AES256_GCM,data:KfVCF1AbSCkLWWbHCl8/lFINrIYVbRb8mQqrvHj8oMN4EAAtgLl5wi8qqnQ3mppEd41apt7W5PuuoDP+xWIg,iv:zd30PhI9qAb+8VoTNbAI39twNTvQzpZgnAfNtb6qIHs=,tag:xJ9MxGgpQjVEUlelY5kJWw==,type:str]
sops:
    age:
        - recipient: age182t6rrn2ymaqrmf28xln99kyq0uek62g7yp27am766p9k2z6hpascv5qr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMejhheGJUeWc2dXRKamlP
            TngrelFxM3lGeDdsMUE0Qnl0dlhKSkhRUVVRCjU4VUhzUWNBZGYwWG11Z2RJK3pv
            WnF4MUZCWWVmR2ljTFh1SnUyT1RWUzAKLS0tIHJaZkpRR3l1eHM2c0pYaTZUUm1B
            WEEwaENXU3VHQXdxajVXdUFlY2FWdU0Kl5Q/jP6DQ8Z1m+nEq0EfKNuLSE8cWoZr
            VFGFzv66axTFgM94ldaSocrJWpFwp4zaSD+sC6Q+D931K6tjOX/Obg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T11:15:49Z"
    mac: ENC[AES256_GCM,data:QWYuTfExiP6DMkTLSqUc0/PkBJt9wrUTmvp7GiRZk55OkUvIIjLndEJs531edKUH00VWHHnjsYentYKzBzZneaHkAeprsPTE6j2Jy9dSpfAjqHTJ2XbOJvDaCmdARei9rWkDc2c8Y/Dw54+RxrazsmXplNCpw7IDloS7aDZ7Eyc=,iv:Oi7ttshCwmRxy/4aDeBgphYb2kAJuK+xNixG5jlQonE=,tag:T8psl/J3vRM9W36aRqzRqw==,type:str]
    pgp:
        - created_at: "2026-08-19T13:55:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DD5j8IMh4Q5oSAQdAp+VBjRJRKYfI88UvmEsGvfrmADTVWcIqFhrWuE/YkgYw
            5H2uGRCvGTHc3AaJrBB55/b9Y7de6hBv6BD5AVi2bfFp5N41RieqNGFaentrqlXA
            0l4B28JUrL2ocrWMDKnugDIX4v3ATGMbEiT7t1mbd+UwM7/NpBygjVMSk4HYbhtr
            Brxq5vdJGnV0/h9j9gERtuYhNRBPj/31nl5D1K57djnUGMur7LgdqegK+6QEUF1d
            =XL7d
            -----END PGP MESSAGE-----
          fp: 7B3F36D6C622479E2EAC2E6C6250E02A31E09AFE
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
