apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gtnh-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: gtnh-data
